### ISSUE TITLE
When username in Windows machine has an space on, application crashes when installing certificates

### ISSUE THREAD

**Issue by EdTech101** [OfficeDev/Office-Addin-Scripts#229]
In a  office add-in development environment when executing the command :  npm run dev-server

console output:

```
> office-addin-taskpane-react-js@0.0.1 dev-server C:\Users\Edwin Veroes\Documents\outlook-addin-reactjs
> webpack-dev-server --mode development

The developer certificates have been generated in C:\Users\Edwin Veroes\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
Error: Unable to install the CA certificate. Import-Certificate : A positional parameter cannot be found that accepts argument 'Veroes\.office-addin-dev-certs\ca.crt'.
At line:1 char:1
+ Import-Certificate -CertStoreLocation cert:\CurrentUser\Root C:\Users ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-Certificate], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.CertificateServices.Commands.ImportCertificateCommand


    at C:\Users\Edwin Veroes\Documents\outlook-addin-reactjs\node_modules\office-addin-dev-certs\lib\install.js:58:19
    at Generator.next (<anonymous>)
    at C:\Users\Edwin Veroes\Documents\outlook-addin-reactjs\node_modules\office-addin-dev-certs\lib\install.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Edwin Veroes\Documents\outlook-addin-reactjs\node_modules\office-addin-dev-certs\lib\install.js:4:12)
    at installCaCertificate (C:\Users\Edwin Veroes\Documents\outlook-addin-reactjs\node_modules\office-addin-dev-certs\lib\install.js:47:12)
    at Object.<anonymous> (C:\Users\Edwin Veroes\Documents\outlook-addin-reactjs\node_modules\office-addin-dev-certs\lib\install.js:41:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Edwin Veroes\Documents\outlook-addin-reactjs\node_modules\office-addin-dev-certs\lib\install.js:5:58)
```

this is caused because the resultant .js of the file ./packages/office-addin-dev-certs/src/install.ts outputs in the line 21 for the command for windows the variable "caCertificatePath" without surrounding quotation marks.

![image](https://user-images.githubusercontent.com/25184779/67500247-443d1a00-f637-11e9-8b60-9e304cd508c6.png)

Was able to work around this by adding simple quotation marks to the resultant .js file but changes need to be done to the .ts file in your repo.

![image](https://user-images.githubusercontent.com/25184779/67500822-1dcbae80-f638-11e9-9e31-84411752dbc1.png)

**Comment by LouMM** [comment]
Closing due to no response
