### ISSUE TITLE
Yeoman generator not getting installed in VDI

### ISSUE THREAD

**Issue by Manasa-Palugula** [OfficeDev/Office-Addin-Scripts#340]
Trying to install(with Admin privileges) the Yeoman using "npm install -g yo generator-office" in VDI for Office Word Add-in
All the proxies and registry  are set properly for the VDI, still facing the issue with below error.

Error:
npm install -g yo generator-office
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
C:\Users\Administrator\AppData\Roaming\npm\yo-complete -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js
C:\Users\Administrator\AppData\Roaming\npm\yo -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\yo\lib\cli.js

> yo@3.1.1 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

√ No .bowerrc file in home directory
√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .yo-rc.json file in home directory
√ Node.js version
ErrorClass [RequestError]: getaddrinfo ENOTFOUND registry.npmjs.org
    at ClientRequest.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ENOTFOUND',
  message: 'getaddrinfo ENOTFOUND registry.npmjs.org',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo'
}
× yo version
ErrorClass [RequestError]: getaddrinfo ENOTFOUND registry.npmjs.org
    at ClientRequest.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ENOTFOUND',
  message: 'getaddrinfo ENOTFOUND registry.npmjs.org',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo'
}
√ npm version

Found potential issues on your machine :(
+ generator-office@1.7.6
+ yo@3.1.1
updated 2 packages in 194.549s

**Comment by LouMM** [comment]
We currently do not support VDI environment. Based on the traces this looks to be an environment issue with access to the npm registry.
