### ISSUE TITLE
npm ERR! Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/Office-Addin-Scripts#474]
# Prerequisites

- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Running `npm install` and/or `lerna bootstrap` on a checked out source code should successfully install all packages.

# Current behavior

Installing dependencies after the lerna was updated to v4 fails.

`npm install` command will fail with error

```

> root@ postinstall /workspaces/Office-Addin-Scripts
> lerna bootstrap

lerna notice cli v4.0.0
lerna info versioning independent
lerna info Bootstrapping 17 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'eslint-config-office-addins'
lerna ERR! npm install stderr:
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codespace/.npm/_logs/2021-06-13T19_05_50_191Z-debug.log
lerna ERR! npm install exited 1 in 'eslint-config-office-addins'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@ postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codespace/.npm/_logs/2021-06-13T19_05_50_388Z-debug.log
```

`lerna bootstrap` command will fail with errro

```
info cli using local version of lerna
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Bootstrapping 17 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'eslint-config-office-addins'
lerna ERR! npm install stderr:
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/codespace/.npm/_logs/2021-06-13T19_06_58_363Z-debug.log
lerna ERR! npm install exited 1 in 'eslint-config-office-addins'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Checkout the **master** branch
2. Run `npm install`
3. Installing dependencies will fail.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: **Linux 5.4.0-1047-azure**
* Node version: **14.15.1** and **14.17.0**
* Office version: N/A
* Tool version: N/A

I tested it on two different setups:

```
$node -v
v14.15.1
$ npm -v
6.14.8
$ lerna --version
4.0.0
```

```
$node -v
v14.17.0
$ npm -v
6.14.13
$ lerna --version
4.0.0
```

## Failure Logs

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/codespace/.nvm/versions/node/v14.17.0/bin/node',
1 verbose cli   '/home/codespace/.nvm/versions/node/v14.17.0/bin/npm',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose npm-session 4962df7cd5be22ad
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall office-addin-sso@1.0.42
7 info lifecycle office-addin-sso@1.0.42~preinstall: office-addin-sso@1.0.42
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 3333ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 62ms
14 silly install loadShrinkwrap
15 timing stage:rollbackFailedOptional Completed in 0ms
16 timing stage:runTopLevelLifecycles Completed in 3759ms
17 silly saveTree office-addin-sso@1.0.42
17 silly saveTree ├─┬ @types/cors@2.8.4
17 silly saveTree │ └─┬ @types/express@4.16.0
17 silly saveTree │   ├─┬ @types/body-parser@1.19.0
17 silly saveTree │   │ ├─┬ @types/connect@3.4.34
17 silly saveTree │   │ │ └── @types/node@14.14.36
17 silly saveTree │   │ └── @types/node@14.14.36
17 silly saveTree │   ├─┬ @types/express-serve-static-core@4.17.19
17 silly saveTree │   │ ├── @types/qs@6.9.6
17 silly saveTree │   │ └── @types/range-parser@1.2.3
17 silly saveTree │   └─┬ @types/serve-static@1.13.9
17 silly saveTree │     └── @types/mime@1.3.2
17 silly saveTree ├─┬ @types/es6-promise@3.3.0
17 silly saveTree │ └── es6-promise@4.2.8
17 silly saveTree ├── @types/express@4.16.0
17 silly saveTree ├─┬ @types/jquery@3.5.5
17 silly saveTree │ └── @types/sizzle@2.3.2
17 silly saveTree ├── @types/mocha@5.2.7
17 silly saveTree ├── @types/morgan@1.7.35
17 silly saveTree ├─┬ chalk@3.0.0
17 silly saveTree │ └─┬ ansi-styles@4.3.0
17 silly saveTree │   └─┬ color-convert@2.0.1
17 silly saveTree │     └── color-name@1.1.4
17 silly saveTree ├── commander@6.2.1
17 silly saveTree ├─┬ concurrently@6.0.0
17 silly saveTree │ ├─┬ chalk@4.1.0
17 silly saveTree │ │ └─┬ supports-color@7.2.0
17 silly saveTree │ │   └── has-flag@4.0.0
17 silly saveTree │ ├── date-fns@2.19.0
17 silly saveTree │ ├── lodash@4.17.21
17 silly saveTree │ └── supports-color@8.1.1
17 silly saveTree ├─┬ cookie-parser@1.4.5
17 silly saveTree │ ├── cookie-signature@1.0.6
17 silly saveTree │ └── cookie@0.4.0
17 silly saveTree ├─┬ cors@2.8.5
17 silly saveTree │ └── object-assign@4.1.1
17 silly saveTree ├─┬ cpy-cli@3.1.1
17 silly saveTree │ ├─┬ cpy@8.1.2
17 silly saveTree │ │ ├── arrify@2.0.1
17 silly saveTree │ │ ├─┬ cp-file@7.0.0
17 silly saveTree │ │ │ ├── graceful-fs@4.2.6
17 silly saveTree │ │ │ ├─┬ make-dir@3.1.0
17 silly saveTree │ │ │ │ └── semver@6.3.0
17 silly saveTree │ │ │ └── nested-error-stacks@2.1.0
17 silly saveTree │ │ ├─┬ globby@9.2.0
17 silly saveTree │ │ │ ├─┬ @types/glob@7.1.3
17 silly saveTree │ │ │ │ └── @types/minimatch@3.0.4
17 silly saveTree │ │ │ ├─┬ array-union@1.0.2
17 silly saveTree │ │ │ │ └── array-uniq@1.0.3
17 silly saveTree │ │ │ ├── dir-glob@2.2.2
17 silly saveTree │ │ │ ├─┬ fast-glob@2.2.7
17 silly saveTree │ │ │ │ ├─┬ @mrmlnc/readdir-enhanced@2.2.1
17 silly saveTree │ │ │ │ │ ├── call-me-maybe@1.0.1
17 silly saveTree │ │ │ │ │ └── glob-to-regexp@0.3.0
17 silly saveTree │ │ │ │ ├── @nodelib/fs.stat@1.1.3
17 silly saveTree │ │ │ │ ├─┬ glob-parent@3.1.0
17 silly saveTree │ │ │ │ │ └─┬ is-glob@3.1.0
17 silly saveTree │ │ │ │ │   └── is-extglob@2.1.1
17 silly saveTree │ │ │ │ ├── is-glob@4.0.1
17 silly saveTree │ │ │ │ ├── merge2@1.4.1
17 silly saveTree │ │ │ │ └─┬ micromatch@3.1.10
17 silly saveTree │ │ │ │   ├── arr-diff@4.0.0
17 silly saveTree │ │ │ │   ├── array-unique@0.3.2
17 silly saveTree │ │ │ │   ├─┬ braces@2.3.2
17 silly saveTree │ │ │ │   │ ├── arr-flatten@1.1.0
17 silly saveTree │ │ │ │   │ ├─┬ extend-shallow@2.0.1
17 silly saveTree │ │ │ │   │ │ └── is-extendable@0.1.1
17 silly saveTree │ │ │ │   │ ├─┬ fill-range@4.0.0
17 silly saveTree │ │ │ │   │ │ ├── extend-shallow@2.0.1
17 silly saveTree │ │ │ │   │ │ └─┬ is-number@3.0.0
17 silly saveTree │ │ │ │   │ │   └─┬ kind-of@3.2.2
17 silly saveTree │ │ │ │   │ │     └── is-buffer@1.1.6
17 silly saveTree │ │ │ │   │ └── isobject@3.0.1
17 silly saveTree │ │ │ │   ├─┬ define-property@2.0.2
17 silly saveTree │ │ │ │   │ └─┬ is-descriptor@1.0.2
17 silly saveTree │ │ │ │   │   ├─┬ is-accessor-descriptor@1.0.0
17 silly saveTree │ │ │ │   │   │ └── kind-of@6.0.3
17 silly saveTree │ │ │ │   │   ├── is-data-descriptor@1.0.0
17 silly saveTree │ │ │ │   │   └── kind-of@6.0.3
17 silly saveTree │ │ │ │   ├─┬ extend-shallow@3.0.2
17 silly saveTree │ │ │ │   │ ├── assign-symbols@1.0.0
17 silly saveTree │ │ │ │   │ └─┬ is-extendable@1.0.1
17 silly saveTree │ │ │ │   │   └── is-plain-object@2.0.4
17 silly saveTree │ │ │ │   ├─┬ extglob@2.0.4
17 silly saveTree │ │ │ │   │ ├─┬ define-property@1.0.0
17 silly saveTree │ │ │ │   │ │ └─┬ is-descriptor@1.0.2
17 silly saveTree │ │ │ │   │ │   ├── is-accessor-descriptor@1.0.0
17 silly saveTree │ │ │ │   │ │   └── is-data-descriptor@1.0.0
17 silly saveTree │ │ │ │   │ ├─┬ expand-brackets@2.1.4
17 silly saveTree │ │ │ │   │ │ ├─┬ debug@2.6.9
17 silly saveTree │ │ │ │   │ │ │ └── ms@2.0.0
17 silly saveTree │ │ │ │   │ │ ├─┬ define-property@0.2.5
17 silly saveTree │ │ │ │   │ │ │ └─┬ is-descriptor@0.1.6
17 silly saveTree │ │ │ │   │ │ │   ├─┬ is-accessor-descriptor@0.1.6
17 silly saveTree │ │ │ │   │ │ │   │ └── kind-of@3.2.2
17 silly saveTree │ │ │ │   │ │ │   ├─┬ is-data-descriptor@0.1.4
17 silly saveTree │ │ │ │   │ │ │   │ └── kind-of@3.2.2
17 silly saveTree │ │ │ │   │ │ │   └── kind-of@5.1.0
17 silly saveTree │ │ │ │   │ │ └── extend-shallow@2.0.1
17 silly saveTree │ │ │ │   │ ├── extend-shallow@2.0.1
17 silly saveTree │ │ │ │   │ └─┬ fragment-cache@0.2.1
17 silly saveTree │ │ │ │   │   └── map-cache@0.2.2
17 silly saveTree │ │ │ │   ├── fragment-cache@0.2.1
17 silly saveTree │ │ │ │   ├── kind-of@6.0.3
17 silly saveTree │ │ │ │   ├─┬ nanomatch@1.2.13
17 silly saveTree │ │ │ │   │ ├── is-windows@1.0.2
17 silly saveTree │ │ │ │   │ └── object.pick@1.3.0
17 silly saveTree │ │ │ │   └── object.pick@1.3.0
17 silly saveTree │ │ │ ├─┬ glob@7.1.6
17 silly saveTree │ │ │ │ ├── fs.realpath@1.0.0
17 silly saveTree │ │ │ │ ├── inflight@1.0.6
17 silly saveTree │ │ │ │ ├── inherits@2.0.4
17 silly saveTree │ │ │ │ └─┬ minimatch@3.0.4
17 silly saveTree │ │ │ │   └─┬ brace-expansion@1.1.11
17 silly saveTree │ │ │ │     ├── balanced-match@1.0.0
17 silly saveTree │ │ │ │     └── concat-map@0.0.1
17 silly saveTree │ │ │ └── ignore@4.0.6
17 silly saveTree │ │ ├─┬ has-glob@1.0.0
17 silly saveTree │ │ │ └── is-glob@3.1.0
17 silly saveTree │ │ ├── junk@3.1.0
17 silly saveTree │ │ └── nested-error-stacks@2.1.0
17 silly saveTree │ └─┬ meow@6.1.1
17 silly saveTree │   ├── @types/minimist@1.2.1
17 silly saveTree │   ├─┬ camelcase-keys@6.2.2
17 silly saveTree │   │ ├── camelcase@5.3.1
17 silly saveTree │   │ └── map-obj@4.2.0
17 silly saveTree │   ├─┬ decamelize-keys@1.1.0
17 silly saveTree │   │ ├── decamelize@1.2.0
17 silly saveTree │   │ └── map-obj@1.0.1
17 silly saveTree │   ├── hard-rejection@2.1.0
17 silly saveTree │   ├─┬ minimist-options@4.1.0
17 silly saveTree │   │ ├── arrify@1.0.1
17 silly saveTree │   │ └── is-plain-obj@1.1.0
17 silly saveTree │   ├─┬ normalize-package-data@2.5.0
17 silly saveTree │   │ └── hosted-git-info@2.8.9
17 silly saveTree │   ├── type-fest@0.13.1
17 silly saveTree │   └── yargs-parser@18.1.3
17 silly saveTree ├── dotenv@8.2.0
17 silly saveTree ├─┬ express@4.17.1
17 silly saveTree │ ├─┬ accepts@1.3.7
17 silly saveTree │ │ ├─┬ mime-types@2.1.29
17 silly saveTree │ │ │ └── mime-db@1.46.0
17 silly saveTree │ │ └── negotiator@0.6.2
17 silly saveTree │ ├── array-flatten@1.1.1
17 silly saveTree │ ├─┬ body-parser@1.19.0
17 silly saveTree │ │ ├── bytes@3.1.0
17 silly saveTree │ │ ├── content-type@1.0.4
17 silly saveTree │ │ ├── depd@1.1.2
17 silly saveTree │ │ ├─┬ http-errors@1.7.2
17 silly saveTree │ │ │ └── inherits@2.0.3
17 silly saveTree │ │ └── iconv-lite@0.4.24
17 silly saveTree │ ├── content-disposition@0.5.3
17 silly saveTree │ ├── content-type@1.0.4
17 silly saveTree │ ├── depd@1.1.2
17 silly saveTree │ ├── encodeurl@1.0.2
17 silly saveTree │ ├── escape-html@1.0.3
17 silly saveTree │ ├── etag@1.8.1
17 silly saveTree │ ├── finalhandler@1.1.2
17 silly saveTree │ ├── fresh@0.5.2
17 silly saveTree │ ├── merge-descriptors@1.0.1
17 silly saveTree │ └── methods@1.1.2
17 silly saveTree ├── form-urlencoded@3.0.0
17 silly saveTree ├─┬ http-errors@1.6.3
17 silly saveTree │ ├── inherits@2.0.3
17 silly saveTree │ └── setprototypeof@1.1.0
17 silly saveTree ├── jquery@3.5.1
17 silly saveTree ├─┬ mocha@7.2.0
17 silly saveTree │ ├── ansi-colors@3.2.3
17 silly saveTree │ ├── browser-stdout@1.3.1
17 silly saveTree │ ├─┬ chokidar@3.3.0
17 silly saveTree │ │ ├─┬ anymatch@3.1.1
17 silly saveTree │ │ │ └── normalize-path@3.0.0
17 silly saveTree │ │ ├─┬ braces@3.0.2
17 silly saveTree │ │ │ └─┬ fill-range@7.0.1
17 silly saveTree │ │ │   └─┬ to-regex-range@5.0.1
17 silly saveTree │ │ │     └── is-number@7.0.0
17 silly saveTree │ │ ├── fsevents@2.1.3
17 silly saveTree │ │ ├── glob-parent@5.1.2
17 silly saveTree │ │ ├─┬ is-binary-path@2.1.0
17 silly saveTree │ │ │ └── binary-extensions@2.2.0
17 silly saveTree │ │ └── normalize-path@3.0.0
17 silly saveTree │ ├─┬ debug@3.2.6
17 silly saveTree │ │ └── ms@2.1.1
17 silly saveTree │ ├── diff@3.5.0
17 silly saveTree │ ├── escape-string-regexp@1.0.5
17 silly saveTree │ ├─┬ find-up@3.0.0
17 silly saveTree │ │ └─┬ locate-path@3.0.0
17 silly saveTree │ │   ├── p-locate@3.0.0
17 silly saveTree │ │   └── path-exists@3.0.0
17 silly saveTree │ ├── glob@7.1.3
17 silly saveTree │ ├── growl@1.10.5
17 silly saveTree │ ├── he@1.2.0
17 silly saveTree │ ├─┬ js-yaml@3.13.1
17 silly saveTree │ │ ├── argparse@1.0.10
17 silly saveTree │ │ └── esprima@4.0.1
17 silly saveTree │ ├─┬ log-symbols@3.0.0
17 silly saveTree │ │ └─┬ chalk@2.4.2
17 silly saveTree │ │   ├─┬ ansi-styles@3.2.1
17 silly saveTree │ │   │ └─┬ color-convert@1.9.3
17 silly saveTree │ │   │   └── color-name@1.1.3
17 silly saveTree │ │   └─┬ supports-color@5.5.0
17 silly saveTree │ │     └── has-flag@3.0.0
17 silly saveTree │ ├─┬ mkdirp@0.5.5
17 silly saveTree │ │ └── minimist@1.2.5
17 silly saveTree │ ├── ms@2.1.1
17 silly saveTree │ ├─┬ node-environment-flags@1.0.6
17 silly saveTree │ │ └─┬ object.getownpropertydescriptors@2.1.2
17 silly saveTree │ │   ├─┬ call-bind@1.0.2
17 silly saveTree │ │   │ ├── function-bind@1.1.1
17 silly saveTree │ │   │ └─┬ get-intrinsic@1.1.1
17 silly saveTree │ │   │   ├── has-symbols@1.0.1
17 silly saveTree │ │   │   └── has@1.0.3
17 silly saveTree │ │   ├─┬ define-properties@1.1.3
17 silly saveTree │ │   │ └── object-keys@1.1.1
17 silly saveTree │ │   └─┬ es-abstract@1.18.0
17 silly saveTree │ │     ├─┬ es-to-primitive@1.2.1
17 silly saveTree │ │     │ ├── is-callable@1.2.3
17 silly saveTree │ │     │ ├── is-date-object@1.0.2
17 silly saveTree │ │     │ └── is-symbol@1.0.3
17 silly saveTree │ │     ├── has-symbols@1.0.2
17 silly saveTree │ │     ├── is-callable@1.2.3
17 silly saveTree │ │     ├── is-negative-zero@2.0.1
17 silly saveTree │ │     ├── is-regex@1.1.2
17 silly saveTree │ │     ├── is-string@1.0.5
17 silly saveTree │ │     ├── object-inspect@1.9.0
17 silly saveTree │ │     └── object.assign@4.1.2
17 silly saveTree │ ├── object.assign@4.1.0
17 silly saveTree │ ├─┬ supports-color@6.0.0
17 silly saveTree │ │ └── has-flag@3.0.0
17 silly saveTree │ ├── yargs-parser@13.1.2
17 silly saveTree │ └─┬ yargs@13.3.2
17 silly saveTree │   ├─┬ cliui@5.0.0
17 silly saveTree │   │ ├─┬ string-width@3.1.0
17 silly saveTree │   │ │ ├── emoji-regex@7.0.3
17 silly saveTree │   │ │ ├── is-fullwidth-code-point@2.0.0
17 silly saveTree │   │ │ └─┬ strip-ansi@5.2.0
17 silly saveTree │   │ │   └── ansi-regex@4.1.0
17 silly saveTree │   │ ├── strip-ansi@5.2.0
17 silly saveTree │   │ └─┬ wrap-ansi@5.1.0
17 silly saveTree │   │   └─┬ ansi-styles@3.2.1
17 silly saveTree │   │     └─┬ color-convert@1.9.3
17 silly saveTree │   │       └── color-name@1.1.3
17 silly saveTree │   ├── get-caller-file@2.0.5
17 silly saveTree │   ├── string-width@3.1.0
17 silly saveTree │   └── y18n@4.0.1
17 silly saveTree ├─┬ morgan@1.9.1
17 silly saveTree │ └── basic-auth@2.0.1
17 silly saveTree └── node-fetch@2.6.1
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:95:20)
18 verbose stack     at inflatableChild (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:121:22)
18 verbose stack     at /home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:63:12
18 verbose stack     at tryCatcher (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Object.gotValue (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
18 verbose stack     at Object.gotAccum (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
18 verbose stack     at Object.tryCatcher (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Promise._settlePromiseFromHandler (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
18 verbose stack     at Promise._settlePromise (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
18 verbose stack     at Promise._settlePromise0 (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
18 verbose stack     at Promise._settlePromises (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
18 verbose stack     at _drainQueueStep (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
18 verbose stack     at _drainQueue (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
18 verbose stack     at Async._drainQueues (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
18 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/home/codespace/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
18 verbose stack     at processImmediate (internal/timers.js:462:21)
19 verbose cwd /workspaces/Office-Addin-Scripts/packages/office-addin-sso
20 verbose Linux 5.4.0-1047-azure
21 verbose argv "/home/codespace/.nvm/versions/node/v14.17.0/bin/node" "/home/codespace/.nvm/versions/node/v14.17.0/bin/npm" "install"
22 verbose node v14.17.0
23 verbose npm  v6.14.13
24 error Cannot read property 'match' of undefined
25 verbose exit [ 1, true ]
```

**Comment by millerds** [comment]
There are two parts of the office-addin-script repro that will encounter the problem (office-addin-sso is one of them, but I don't recall the other).  The way I found to fix this is to delete the node_modules folder and the package-lock.json files of those packages and then run the 'npm install' fresh.  I don't think there is anything that can be checked into the repro to avoid this.

**Comment by jozefizso** [comment]
This will change a lot of stuff in the `package-lock.json` (and it fixes the issue).

Should these updated package-lock files be commited?

**Comment by akrantz** [comment]
@jozefizso If you're running into this for your local clone of the repo, you can also run that command (npm run clean-install-packages) to fix it for you locally.

**Comment by jozefizso** [comment]
I ran it in the GitHub Codespace so it was a clean machine.

**Comment by millerds** [comment]
If there is any further problems with this please let us know.
