### ISSUE TITLE
Impossible to mock excel properties

### ISSUE THREAD

**Issue by johnrazeur** [OfficeDev/Office-Addin-Scripts#602]
# Current behavior

I have an error when I define a `properties` in the mock, because the `OfficeMockObject` already have a `properties` property.

## Steps to Reproduce

```ts
const mockData = {
    context: {
        workbook: {
          properties: {
            custom: { ... }
          }
        }
    },
}
const excelMock = new OfficeMockObject(mockData);
```

## Context

* Operating System: MacOS
* Node version: 14.17.3
* Office version: 16.57
* Tool version: 2.1.0

## Failure Logs

```
 Mock object already exists

      at OfficeMockObject.addMock (node_modules/office-addin-mock/src/officeMockObject.ts:74:10)
      at node_modules/office-addin-mock/src/officeMockObject.ts:186:8
          at Array.forEach (<anonymous>)
      at OfficeMockObject.populate (node_modules/office-addin-mock/src/officeMockObject.ts:183:8)
      at node_modules/office-addin-mock/src/officeMockObject.ts:187:4
          at Array.forEach (<anonymous>)
      at OfficeMockObject.populate (node_modules/office-addin-mock/src/officeMockObject.ts:183:8)
      at node_modules/office-addin-mock/src/officeMockObject.ts:187:4
          at Array.forEach (<anonymous>)
      at OfficeMockObject.populate (node_modules/office-addin-mock/src/officeMockObject.ts:183:8)
```

**Comment by igor-ribeiiro** [comment]
[johnrazeur](https://github.com/johnrazeur) thanks for raising this issue. It is a real problem and I just made a PR https://github.com/OfficeDev/Office-Addin-Scripts/pull/604 to fix it.
Please, expect this to be live in the next version update we made to the package.
