### ISSUE TITLE
Excel SSO addin Issue

### ISSUE THREAD

**Issue by SenMS-CSA** [OfficeDev/Office-Addin-Scripts#887]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

It should launch Azure for creating application configuration

# Current behavior

I am getting below error message while running  npm run configure-sso with excel SSO addin

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "'az' is not recognized as an internal or external command,
operable program or batch file.
".
    at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
  code: 'ERR_UNHANDLED_REJECTION'
}

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  create the office addin with sso for excel template
2. run: npm run configure-sso
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Node version:
* Office version:
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by Rick-Kirkham** [comment]
This is an issue with the office-addin-sso package of the Office-Addin-Scripts repo, so I'm moving it to that repo.

**Comment by SenMS-CSA** [comment]
> This is an issue with the office-addin-sso package of the Office-Addin-Scripts repo, so I'm moving it to that repo.

Thanks Rick

**Comment by SenMS-CSA** [comment]
Is there any update on this?

**Comment by ndeleuze** [comment]
Hi @SenMS-CSA, would you be able to provide the output from `npm run configure-sso` so I can see how far the call gets before outputting this error?

**Comment by SenMS-CSA** [comment]
> Hi @SenMS-CSA, would you be able to provide the output from `npm run configure-sso` so I can see how far the call gets before outputting this error?
Below is the error

Setting application secret
C:\xxxxx\VSCode\ExcelAzureSSO\MyExcelSsoAddin\node_modules\office-addin-sso\lib\configure.js:215
            throw new Error(errorMessage);
                  ^

Error: Unable to set application secret:
ERROR: Bad Request({"error":{"code":"CredentialTypeNotAllowedAsPerAppPolicy","message":"Credential type not allowed as per assigned policy '538f1913-366a-440a-95a0-e195cb55b282'.","details":[{"code":"InvalidKeyType","message":"Credential type not allowed as per assigned policy '538f1913-366a-440a-95a0-e195cb55b282'.","target":"credential.KeyType","blockedWord":"","prefix":"","suffix":""}],"innerError":{"date":"2024-10-10T23:01:21","request-id":"0bfbb31e-dbb1-4f81-b482-14fd15cee72c","client-request-id":"0bfbb31e-dbb1-4f81-b482-14fd15cee72c"}}})

    at Object.<anonymous> (C:\xxxx\VSCode\ExcelAzureSSO\MyExcelSsoAddin\node_modules\office-addin-sso\lib\configure.js:215:19)
    at Generator.throw (<anonymous>)
    at rejected (C:\xxxxx\VSCode\ExcelAzureSSO\MyExcelSsoAddin\node_modules\office-addin-sso\lib\configure.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ndeleuze** [comment]
@SenMS-CSA I am able to reproduce this issue as well. Thanks for reporting this. It has been put on our backlog. We unfortunately have no timelines to share at this point.
 
Internal tracking id: Office: 9484117
