### ISSUE TITLE
Would it be possible to add a changelog for each package?

### ISSUE THREAD

**Issue by tobiasbueschel** [OfficeDev/Office-Addin-Scripts#913]
It would be great if we could add a `changelog.md` to each of the packages and also detail the package changelog in each GitHub release and tag that is pushed to this monorepo.

**For context:**
- Various packages were recently updated such as `office-addin-debugging to v6.0.1`  and `office-addin-manifest to v2.0.1`
- I was trying to find the changelog for each of updates made in the respective package so that I could understand what impact it would have if I were to update these packages to the latest version
- One could go through the [commit history](https://github.com/OfficeDev/Office-Addin-Scripts/commits/master/), but that's not ideal

**Potential solutions**
There are some off-the-shelf tools available for automatically updating monorepo packages semantic versions based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

- [semantic-release](https://github.com/semantic-release/semantic-release) - auto updates the semantic version
- [release-please](https://github.com/googleapis/release-please) - raises a PR with a new proposed version update. My preferred approach

**Comment by tobiasbueschel** [comment]
I've tried to upgrade to v6.0.1 of the `office-addin-debugging` package, but now receive the following error:

```
> demo-project@2.2.0 ostop /Users/tobias/demo-project
> office-addin-debugging stop manifest.xml

/Users/tobias/demo-project/node_modules/.pnpm/office-addin-debugging@6.0.1_@microsoft+teamsapp-cli@3.0.2_bufferutil@4.0.8/node_modules/office-addin-debugging/lib/defaults.js:11
exports.usageDataObject = new office_addin_usage_data_1.default.OfficeAddinUsageData({
                                                                ^

TypeError: Cannot read properties of undefined (reading 'OfficeAddinUsageData')
    at Object.<anonymous> (/Users/tobias/demo-project/node_modules/.pnpm/office-addin-debugging@6.0.1_@microsoft+teamsapp-cli@3.0.2_bufferutil@4.0.8/node_modules/office-addin-debugging/lib/defaults.js:11:65)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1325:12)
    at Module.patchedRequire [as require] (/Users/tobias/demo-project/node_modules/.pnpm/diagnostic-channel@0.3.1/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (node:internal/modules/helpers:136:16)

Node.js v23.3.0
 ELIFECYCLE  Command failed with exit code 1.
 ```
 
 Would you mind pointing me to what changed? :)

**Comment by millerds** [comment]
Thank you for reporting this bug.  I have logged an internal tracking item for this (id: 9684299) for follow up.  Unfortunately, we cannot comment on potential timelines for a fix.  In the meantime, you can always just set the errorMessage property to get the desired behavior.

**Comment by millerds** [comment]
Thanks for the suggestion on the release notes.  Those suggested package don't fit within our current process, but our process could use some refinement, so we'll have to consider those libraries.

The last major version bump of these packages was due to a restructuring of many of the typescript configuration controlling the build process.  They have not been pushed as the latest packages because they still need to go through some validation with some test projects to make sure some something else hasn't broken.  If I had to wager a guess, I'd say either you don't have the updated OfficeAddinUsageDate and it's needed (though I'm not sure why) or something did break between OfficeAddinUsageData and OfficeAddinDebugging.

Could you try installing the "next" version of OfficeAddinUsageData directly in your project and see if you get different behavior?

**Comment by millerds** [comment]
Actually . . . that won't work.  Looks like the generated import statement (typescript to js in the package) changed when the typescript build confg was updated and that is not working even though the updated office-addin-usage-data package is installed.  This is a bug in the packages that needs to get fixed before making these versions the "latest" versions.

**Comment by millerds** [comment]
New official version of the packages have been posed now with the bug fixed.  They should work.

We'll have to look into change logs.

**Comment by MAValentino** [comment]
Any update on adding changelogs? I was about to upgrade a package to a new major version, but held off on it because I couldn't find what the possible breaking changes were.
